#!/bin/sh
head () {
if ! grep -q "{" "$temp"; then
	echo "$(grep "${1#.}" "$temp")" > "$temp"
	sed 's/[[:space:]]//g' -i "$temp"
	IFS=':'; read -r var val < "$temp"
	case "$val" in
		"")
			echo "Whoops!! Can't find ${1#.}"; exit 1;;
		*)
			echo "${val%,}";;
	esac
else
	sed '/^'"${spa}"'"'"${1#.}"'"''/,$!d' "$orgtemp" > "$temp"
	IFS='"'; read -r end ex < "$temp"
	sed '/^'"${end}"'\}/q' -i "$temp"
	sed 's/"'"${1#.}"'" : {/{/g' -i "$temp"
	sed 's/^'"${end}"'\}\,/}/g' -i "$temp"
	sed 's/^'"${end}"'//' -i "$temp"
	cat "$temp"
fi
}
loop() {
unset IFS
for i in $@; do
	if [ "$i" = "$1" ]; then
		sed '/^'"${spa}"'"'"${i}"'"''/,$!d' "$orgtemp" > "$temp"
	else
		sed '/^'"${spa}"'"'"${i}"'"''/,$!d' -i "$temp"
	fi
if ! grep -q "{" "$temp"; then
	echo "$(grep "${i#.}" "$temp")" > "$temp"
	sed 's/[[:space:]]//g' -i "$temp"
	IFS=':'; read -r var val < "$temp"
	case "$val" in
		"")
			echo "Whoops!! Can't find ${i}"; exit 1;;
		*)
			echo "${val%,}" > "$temp";;
	esac
else
	IFS='"'; read -r end ex < "$temp"
	if ! grep "^${end}"'"'"${i#.}"'" : \[ {' -q "$temp"; then
		sed '/^'"${end}"'\}/q' -i "$temp"
		sed 's/"'"${i#.}"'" : {/{/g' -i "$temp"
	else
		sed '/^'"${end}"'\} ]/q' -i "$temp"
		sed 's/"'"${i#.}"'" : \[ {/\[/g' -i "$temp"
	fi
	sed 's/^'"${end}"'//' -i "$temp"
	if ! grep "^${end}"'"'"${i#.}"'" : \[ {' -q "$temp"; then
		sed 's/^} ],/]/g' -i "$temp"
	else
		sed 's/^\}\,/}/g' -i "$temp"
	fi
fi
done
}
usage() {
	cat << 'EOF'
Jp ~ JsonPosix - POSIX sh json handler
***
usage:
<some json outputting program> | ./jp "<element>"
eg: spotbash get_info | ./jp ".is_playing"
***
~ By Mia
  ~ Also charlotte is a good girl
***
EOF
}
case $1 in
	-h)
		usage && exit 1
		;;
	*)
		orgtemp="$(mktemp)"
		temp="$(mktemp)"
		spatemp="$(mktemp)"
		# idtemp="$(mktemp)"
		cat > "$orgtemp" # jp is meant to read from a pipe
		grep '\s*"' -m 1 < "$orgtemp" > "$spatemp"
		IFS='"'; read -r spa ex < "$spatemp" # set space count
		grep "^${spa}"'"'"${1#.}"'"' "$orgtemp" > "$temp"
		if ! [ $(echo ${1} | awk -F. '{print NF-1}') -gt 1 ]; then
			head "$1"
		else
			IFS="."; loop ${1#.}
			cat "$temp"
		fi;;
esac
rm "$temp" -rf
rm "$orgtemp" -rf
rm "$spatemp" -rf
